import type { AgentPrompt } from './types'

const sharedConstraints = ['Return JSON matching the requested fields.', 'Preserve approved decisions from the context.', 'Separate assumptions from facts.', 'Do not claim trademark, domain, or market availability.', 'Prefer concrete language over branding cliches.']

export const agentPrompts: AgentPrompt[] = [
  { stage: 'discovery', role: 'Discovery Agent', objective: 'Extract the audience, core problem, context, goals, constraints, assumptions, and high-value open questions.', requiredFields: ['coreProblem', 'targetAudience', 'secondaryAudience', 'userContext', 'userGoals', 'constraints', 'assumptions', 'openQuestions'], constraints: sharedConstraints },
  { stage: 'positioning', role: 'Strategy Agent', objective: 'Turn approved discovery into a defensible category, value proposition, differentiator, positioning statement, and reasons to believe.', requiredFields: ['category', 'targetAudience', 'problem', 'valueProposition', 'differentiator', 'competitiveAngle', 'positioningStatement', 'reasonsToBelieve', 'keyBenefit'], constraints: sharedConstraints },
  { stage: 'personality', role: 'Personality Agent', objective: 'Define 3 to 5 traits with reason, expression, and failure mode, plus traits to avoid.', requiredFields: ['traits', 'traitsToAvoid', 'brandPrinciples'], constraints: sharedConstraints },
  { stage: 'naming', role: 'Naming Agent', objective: 'Generate strategically distinct names tied to the approved positioning and personality.', requiredFields: ['directions', 'name', 'territory', 'rationale', 'weakness', 'personalityAlignment'], constraints: [...sharedConstraints, 'Never imply trademark or domain availability.'] },
  { stage: 'visual', role: 'Visual Direction Agent', objective: 'Translate approved strategy and personality into a connected visual identity direction.', requiredFields: ['typography', 'colorMood', 'primaryColors', 'secondaryColors', 'shapeLanguage', 'composition', 'imagery', 'illustration', 'logoDirection', 'avoid'], constraints: sharedConstraints },
  { stage: 'critic', role: 'Independent AI Critic', objective: 'Challenge generic language, weak assumptions, audience mismatch, differentiation, naming, visual fit, and messaging.', requiredFields: ['overallAssessment', 'issues', 'improvementSuggestions'], constraints: [...sharedConstraints, 'Do not default to praise. Every issue needs a reason and recommendation.'] },
  { stage: 'consistency', role: 'Consistency Guardian', objective: 'Compare the complete brand system and explain pass, warning, or fail checks.', requiredFields: ['score', 'checks', 'improvementsMade'], constraints: sharedConstraints },
  { stage: 'launch', role: 'Launch Agent', objective: 'Create practical launch messages that follow the approved positioning, personality, visual direction, and voice.', requiredFields: ['voice', 'headline', 'subheadline', 'oneLinePitch', 'description', 'announcement', 'socialPost', 'cta', 'founderPitch'], constraints: sharedConstraints },
]
